import { jsPDF } from 'jspdf';
import { BatchAnalysis, DiagnosisResult } from '../types';

export function exportBatchToCSV(batch: BatchAnalysis): void {
  const headers = [
    'Image Name',
    'Plant Name',
    'Plant Confidence (%)',
    'Disease',
    'Disease Confidence (%)',
    'Severity (%)',
    'Severity Level',
    'Timestamp'
  ];

  const list = batch.items || batch.results || [];

  const rows = list.map((item) => [
    `"${(item.fileName || 'sample').replace(/"/g, '""')}"`,
    `"${item.plantName.replace(/"/g, '""')}"`,
    item.plantConfidence,
    `"${item.diseaseName.replace(/"/g, '""')}"`,
    item.diseaseConfidence,
    item.severityPercentage,
    item.severityLevel,
    `"${item.timestamp || batch.createdAt}"`
  ]);

  const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', `CropPulse_Batch_${batch.id || batch.batchId}_Report.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function generateBatchSummaryPDF(batch: BatchAnalysis): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Banner
  doc.setFillColor(22, 101, 52); // Forest Green
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('CROP PULSE | Farmer Batch Pathology Report', 14, 18);

  // Metadata Section
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Batch ID: ${batch.id || batch.batchId}`, 14, 38);
  doc.text(`Batch Name: ${batch.batchName || 'Field Survey'}`, 14, 44);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 50);
  doc.text(`Total Scans: ${batch.totalImages} images`, 14, 56);

  // Summary Metrics Table
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, 62, pageWidth - 28, 30, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Summary Overview`, 20, 71);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Healthy Samples: ${batch.healthyCount ?? batch.healthyImages ?? 0}`, 20, 80);
  doc.text(`Diseased Samples: ${batch.diseasedCount ?? batch.diseasedImages ?? 0}`, 20, 86);
  doc.text(`Average Severity: ${batch.averageSeverity}%`, 110, 80);
  doc.text(`Dominant Disease: ${batch.dominantDisease || 'N/A'}`, 110, 86);

  // Detailed Analysis Table Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Individual Leaf Diagnoses', 14, 102);

  let y = 110;
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, pageWidth - 28, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text('File Name', 16, y + 5.5);
  doc.text('Plant Species', 65, y + 5.5);
  doc.text('Disease Diagnosis', 115, y + 5.5);
  doc.text('Severity', 165, y + 5.5);
  doc.text('Level', 185, y + 5.5);

  y += 9;
  doc.setTextColor(51, 65, 85);
  doc.setFont('helvetica', 'normal');

  const list = batch.items || batch.results || [];

  list.slice(0, 25).forEach((item, index) => {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }

    if (index % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y - 4, pageWidth - 28, 7, 'F');
    }

    const shortName = (item.fileName || 'leaf_sample').length > 20 ? (item.fileName || 'leaf_sample').substring(0, 18) + '...' : (item.fileName || 'leaf_sample');
    const shortPlant = item.plantName.length > 22 ? item.plantName.substring(0, 20) + '...' : item.plantName;
    const shortDisease = item.diseaseName.length > 24 ? item.diseaseName.substring(0, 22) + '...' : item.diseaseName;

    doc.text(shortName, 16, y);
    doc.text(shortPlant, 65, y);
    doc.text(shortDisease, 115, y);
    doc.text(`${item.severityPercentage}%`, 165, y);
    doc.text(item.severityLevel, 185, y);

    y += 7;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Crop Pulse AI Health Engine • Confidential Agricultural Report', 14, 290);

  doc.save(`CropPulse_Report_${batch.id || batch.batchId}.pdf`);
}

export const generateBatchPDFReport = generateBatchSummaryPDF;

export function generateSingleDiagnosisPDF(diag: DiagnosisResult): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(22, 101, 52);
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('CROP PULSE | Leaf Disease Diagnosis Certificate', 14, 18);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Diagnosis ID: ${diag.id}`, 14, 38);
  doc.text(`Date & Time: ${new Date(diag.timestamp).toLocaleString()}`, 14, 44);
  doc.text(`AI Model: ${diag.modelVersion}`, 14, 50);

  // Diagnosis Box
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, 58, pageWidth - 28, 48, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`Plant: ${diag.plantName} (${diag.plantConfidence}% conf.)`, 20, 70);

  doc.setFontSize(12);
  doc.setTextColor(diag.severityPercentage > 30 ? 185 : 22, diag.severityPercentage > 30 ? 28 : 101, 28);
  doc.text(`Disease: ${diag.diseaseName} (${diag.diseaseConfidence}% conf.)`, 20, 80);

  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Severity: ${diag.severityPercentage}%  •  Severity Level: ${diag.severityLevel}`, 20, 90);
  doc.text(`Symptoms: ${diag.symptoms || 'Visible lesion and tissue distortion.'}`, 20, 98);

  // Recommended Mitigation Actions
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Actionable Agronomy Recommendations', 14, 120);

  let y = 130;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('1. Immediate Actions:', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const imm = diag.recommendations.immediate || diag.recommendations.immediateActions || [];
  imm.forEach(act => {
    doc.text(`• ${act}`, 18, y);
    y += 5.5;
  });

  y += 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('2. Treatment & Fungicide Guidance:', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const treat = diag.recommendations.treatment || diag.recommendations.chemicalTreatments || [];
  treat.forEach(act => {
    doc.text(`• ${act}`, 18, y);
    y += 5.5;
  });

  y += 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('3. Preventive Practices:', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const prev = diag.recommendations.preventive || diag.recommendations.preventiveMeasures || [];
  prev.forEach(act => {
    doc.text(`• ${act}`, 18, y);
    y += 5.5;
  });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Crop Pulse Agricultural Intelligence • Verify with local agricultural extension officer.', 14, 288);

  doc.save(`CropPulse_Diagnosis_${diag.id}.pdf`);
}
